Merge branch Feature/aggregate statistics generator into develop
UniversityOfSaskatchewanCMPT371/term-project-2024-team-4 pull request #109
Opened 2024-03-17 03:46 UTC by AdamStanger

Files added:

- frontend/src/components/StatisticsPage.jsx: Page containing the tabe for all the projectile points in the catalogue
- frontend/src/components/StatisticsModal.jsx: Modal for displaying charts for the generated statistics
- frontend/tests/statisticsPage.unit.test.jsx

Modifications:

- Functions in backend/controllers/aggregateStatisticsGenerator.js changed to be async to fix issue when passing data to the frontend
- Unit tests for those functions updated based on refactor
- Path to statistics page added (localhost:8080/stats)

2024-03-22 01:44 UTC, lecegues requested changes
Please view my comments for some changes. 
Additionally, am I correct in assuming that all of the `routes` were changed because they now use the corresponding `helperFile`? Or were the changes to the `route` files accidental from the merge?

2024-03-22 01:44 UTC, lecegues commented on backend/config/authenticate.js
This file should be deleted (remnants from the merge from develop). This file was moved to the `middleware` folder

2024-03-22 01:44 UTC, lecegues commented on backend/package.json
This should **not** get rid of these scripts and dependencies. Could be a mistake from the merge from develop.

2024-03-22 01:44 UTC, lecegues commented on frontend/package.json
@vitest/coverage-v8 package should **not** be touched. Again, probably something missed due to the merge.

2024-03-22 01:44 UTC, lecegues commented on frontend/src/components/Home.jsx
Was box supposed to be first or not? If I remember, I know that the order of dependencies can sometimes cause MUI to crash... Please verify

2024-03-22 01:44 UTC, lecegues commented on frontend/tests/setup.js
As long as this addition to `setup.js` does not interfere with other tests, then it is ok. Just noting this because **every test** will be referencing this `setup.js` file.

2024-03-22 01:48 UTC, brj496 commented
> Please view my comments for some changes. Additionally, am I correct in assuming that all of the `routes` were changed because they now use the corresponding `helperFile`? Or were the changes to the `route` files accidental from the merge?

each route was changed to use its corresponding helperFile. They are correct as they are right now

2024-03-22 01:54 UTC, brj496 commented on frontend/src/components/Home.jsx
I'm not sure, I don't remember messing with this file, so it may have been changed due to the merge

2024-03-22 02:22 UTC, brj496 commented on backend/config/authenticate.js
Removed authenticate.js from backend config

2024-03-22 02:22 UTC, brj496 commented on backend/package.json
Made sure to add back removed dependencies

2024-03-22 02:22 UTC, brj496 commented on frontend/src/components/Home.jsx
turns out they are in the right order

2024-03-22 02:23 UTC, brj496 commented on frontend/tests/setup.js
I think Dani is the one who made this file, but all the tests function on my machine.

2024-03-22 02:27 UTC, lecegues requested changes

2024-03-22 02:27 UTC, lecegues commented on testing/smoke-test/smoke.spec.js
You've accidentally added back the smoke tests that were removed, and accidentally removed the new smoke test(edge cases). Please change this

2024-03-22 02:38 UTC, brj496 commented on testing/smoke-test/smoke.spec.js
added back new tests and removed old tests

2024-03-22 02:39 UTC, lecegues approved these changes
Reviewed changes were fixed.

2024-03-25 03:21 UTC, lecegues requested changes
There are some API requests that call different helpers than what is intended. I have outlined which ones need ot be changed

2024-03-25 03:21 UTC, lecegues commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
GET request, but calling a POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
GET request, calling POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
PUT req, calling a POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
DELETE req, using a POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/crossSections.js
> +	const response = await crossSectionsHelper.updateCrossSection(req);
DELETE req, using UPDATE helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/materials.js
> +	const response = await materialsHelper.newMaterial(req);
GET req, calling a POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/materials.js
> +	const response = await materialsHelper.newMaterial(req);
UPDATE req, calling a POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/materials.js
> +	const response = await materialsHelper.newMaterial(req);
DELETE req, calling a POST helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/periods.js
> +	const response = await periodsHelper.updatePeriod(req);
DELETE req, calling UPDATE helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
POST req, calling a GET helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
SINGLE GET req, calling a GET ALL helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
UPDATE req, calling a GET helper

2024-03-25 03:21 UTC, lecegues commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
DELETE req, calling a GET helper

2024-03-25 03:31 UTC, brj496 commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:31 UTC, brj496 commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:31 UTC, brj496 commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:35 UTC, brj496 commented on backend/routes/artifacts.js
> +	const response = await artifactsHelper.newArtifact(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:35 UTC, brj496 commented on backend/routes/crossSections.js
> +	const response = await crossSectionsHelper.updateCrossSection(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:35 UTC, brj496 commented on backend/routes/materials.js
> +	const response = await materialsHelper.newMaterial(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:35 UTC, brj496 commented on backend/routes/materials.js
> +	const response = await materialsHelper.newMaterial(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:36 UTC, brj496 commented on backend/routes/materials.js
> +	const response = await materialsHelper.newMaterial(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:36 UTC, brj496 commented on backend/routes/periods.js
> +	const response = await periodsHelper.updatePeriod(req);
Fixed Issue, replaced with correct function call

2024-03-25 03:36 UTC, brj496 commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
Fixed Issue, replaced with correct function call

2024-03-25 03:36 UTC, brj496 commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
Fixed Issue, replaced with correct function call

2024-03-25 03:36 UTC, brj496 commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
Fixed Issue, replaced with correct function call

2024-03-25 03:36 UTC, brj496 commented on backend/routes/regions.js
> +	const response = await regionsHelper.getAllRegions();
Fixed Issue, replaced with correct function call

2024-03-25 07:15 UTC, lecegues approved these changes
Reviewed changes were fixed. Additionally, some tests stopped working which revealed some bugs (#115) and were fixed. Also removed failing `Login.integ.test.jsx`; refer to issue #116. Branch should be good for merge.

2024-03-25 18:57 UTC, funmise approved these changes
Helper files are a good change to the routes

2024-03-25 19:54 UTC, merged