feature/projectile
UniversityOfSaskatchewanCMPT371/term-project-2024-team-4 pull request #111
Opened 2024-03-17 06:31 UTC by keliboi

Merge feature branch for ID4 submission requirements

2024-03-18 03:25 UTC, funmise reviewed
need to fix rollup issue. might need to add it as optional dependency

2024-03-24 21:36 UTC, funmise requested changes
Going forward, the integration tests should be made more rigorous to ensure that the request is actually carried out and not just sent i.e . further communication with backend.

2024-03-24 21:36 UTC, funmise commented on frontend/tests/Login.integ.test.js
this file should not be deleted.

2024-03-24 21:36 UTC, funmise commented on frontend/tests/setup.js
> +axios.defaults.baseURL = "http://127.0.0.1:3000";
line 7 not needed. It's redundant.

2024-03-24 21:40 UTC, keliboi commented on frontend/tests/Login.integ.test.js
Login.integ.test.js added back to branch

2024-03-24 21:41 UTC, keliboi commented on frontend/tests/setup.js
> +axios.defaults.baseURL = "http://127.0.0.1:3000";
Line removed as requested

2024-03-24 21:53 UTC, keliboi commented on frontend/tests/Login.integ.test.js
File was removed again as it is non-functional for this branch, it will be added through a merge with another branch in develop

2024-03-24 21:56 UTC, funmise approved these changes
looks good now

2024-03-24 21:59 UTC, lecegues approved these changes
Updated changes from Babz' review looks good. Good usage of multi-level logging, assertions, and docstrings (compared to past pull requests).

2024-03-24 22:00 UTC, merged