Feature/login backend
UniversityOfSaskatchewanCMPT371/term-project-2024-team-4 pull request #65
Opened 2024-02-28 21:29 UTC by DcGitLoom

2024-03-03 19:40 UTC, lecegues commented on backend/.env
This file should not be here (security risk)

2024-03-06 03:44 UTC, lecegues requested changes
Needs data validation (e.g. spaces, special characters, etc...), use of `logger` not `console.log` and more API Docs

2024-03-06 03:44 UTC, lecegues commented on backend/helpers/register.js
> +const registerUser = async () => {
Include API Docs (pre-conditions, purpose, post-conditions)

2024-03-06 05:40 UTC, lecegues requested changes

2024-03-06 05:40 UTC, lecegues commented on backend/routes/users.js
> +router.post("/", async (req, res) => {
API Docs

2024-03-06 05:40 UTC, lecegues commented on backend/routes/users.js
> +router.post("/logout", async (req, res) => {
API Docs

2024-03-06 05:40 UTC, lecegues commented on backend/routes/users.js
Needs field validation (e.g. right now, spaces will work in usernames and paswords ["hello world"] and should not)

2024-03-06 05:40 UTC, lecegues commented on backend/routes/users.js
Use `logger` middleware rather than `console.log` as it will send logs to log files and have color-coded logs.

2024-03-06 20:48 UTC, lecegues requested changes

2024-03-06 20:48 UTC, lecegues commented on frontend/src/components/LoginModal.jsx
> +		if (userName.length < 5) {
Sorry, Miscommunication upon the required validation feature. **Username and password validation** should be present upon signup/changing username or password. You have changed the `patch` endpoint already, but the change in the `login-modal` is unnecessary

2024-03-06 20:52 UTC, lecegues requested changes

2024-03-06 20:52 UTC, lecegues commented on backend/routes/users.js
> +				throw err;
This throws an error (which effectively crashes the whole backend) if the user does not have a token. Please handle this more gracefully.

2024-03-06 23:31 UTC, lecegues commented on backend/routes/users.js
> +				throw err;
I don't know if this is where the exact error originated from, but a more detailed outlook of the issue is issue #92

2024-03-07 01:38 UTC, lecegues commented on backend/routes/users.js
> +				throw err;
Due to the need for this branch to allow developers to start development for ID4, we will leave this issue for a future patch. (issue #92)

2024-03-07 01:40 UTC, funmise approved these changes
No further comments besides the ones John has already stated. Issue with persistent cookies is still present but I advise merging for now and assigning a fix to new Dev

2024-03-07 01:43 UTC, lecegues approved these changes

2024-03-07 01:47 UTC, merged